#!/bin/sh

#
# MOUNT from hostOS:
#
# Grub is on sda1 primary is on sda2
# Without EFI, sector 4096 and sector size is 512 ==> 2097152
# With EFI, sector 1103872 and sector size is 512 ==> 565182464
#
if [ $1 -eq 0 ]; then
sudo mount -o offset=2097152 disk.img mnt
else
sudo mount -o offset=565182464 disk_efi.img mnt
fi

